spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${CUSTOMIZE_DATASOURCE_URL}
    username: ${CUSTOMIZE_DATASOURCE_USERNAME}
    password: ${CUSTOMIZE_DATASOURCE_PASSWORD}
    hikari:
      max-lifetime: 60000
